import './get-preferences';
import './fetch-users';
import './authenticate';
import './vendors';
import './product-categories';
import './brands';
import './set-preferences';
import './products'
import './sales'
import './sales-payments'
import './customers'
import './sales-reports-metrics'
import './purchase'
import './purchase-payments'
import './purchase-reports-metrics'
import './stocks'
import './expense-categories'
import './expences'
import './dashboard'
import './scraps'
import './productwise-profit'